CREATE TABLE [dbo].[EmployeeProfiles]
(
  [Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
  [EffectiveStartedOn] DATETIME NOT NULL DEFAULT GETDATE(), 
  [EffectiveStartedBy] UNIQUEIDENTIFIER NULL, 
  [EffectiveModifiedOn] DATETIME NOT NULL DEFAULT GETDATE(), 
  [EffectiveModifiedBy] UNIQUEIDENTIFIER NULL, 
  [EffectiveEndedOn] DATETIME NOT NULL, 
  [EffectiveEndedBy] UNIQUEIDENTIFIER NULL,
  [Comment] NVARCHAR(1024) NULL,
  [Text] NVARCHAR(MAX) NULL,
  [Tags] NVARCHAR(250) NULL,
  [EmployeeId] UNIQUEIDENTIFIER NOT NULL,
  [EmployeeSkillSourceId] UNIQUEIDENTIFIER NOT NULL
)
