CREATE TABLE [dbo].[Users]
(
  [Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
  [EffectiveStartedOn] DATETIME NOT NULL DEFAULT GETDATE(), 
  [EffectiveStartedBy] UNIQUEIDENTIFIER NULL, 
  [EffectiveModifiedOn] DATETIME NOT NULL DEFAULT GETDATE(), 
  [EffectiveModifiedBy] UNIQUEIDENTIFIER NULL, 
  [EffectiveEndedOn] DATETIME NOT NULL, 
  [EffectiveEndedBy] UNIQUEIDENTIFIER NULL, 
  [Comment] NVARCHAR(1024) NULL,
  [Active] BIT NOT NULL DEFAULT 1,
  [Login] NVARCHAR(128) NOT NULL,
  [PasswordData] NVARCHAR(2048) NOT NULL, 
  [ExpireDate] DATETIME NULL, 
  [LastLogin] DATETIME NULL, 
  [FailedAttempts] INT NOT NULL DEFAULT 0, 
  [GoodLogins] INT NOT NULL DEFAULT 0, 
  [Firstname] NVARCHAR(150) NOT NULL, 
  [Lastname] NVARCHAR(150) NOT NULL, 
  [Email] NVARCHAR(150) NOT NULL, 
  [EmployeeId] UNIQUEIDENTIFIER NULL
)
